apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: microstore
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - >
              until nc -z mysql-service 3306;
              do echo waiting for mysql;
              sleep 2;
              done;
      containers:
        - name: orders
          image: <TU_REGISTRY>/microstore-orders:latest
          ports:
            - containerPort: 5004
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PORT
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PASSWORD
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_NAME
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_ENV
            - name: FRONTEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_HOST
          readinessProbe:
            httpGet:
              path: /api/orders
              port: 5004
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/orders
              port: 5004
            initialDelaySeconds: 60
            periodSeconds: 30
